grafana:
  adminPassword: apsswrod
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
      - grafana.local
    tls:
      - secretName: prometheus-grafana-tls-secret
        hosts:
          - grafana.local
      