apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonLabels:
  app.kubernetes.io/component: kfserving-install
  app.kubernetes.io/instance: kfserving-install-0.2.2
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: kfserving-install
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.2.2
kind: Kustomization
resources:
- application.yaml
