rbac:
  create: true
controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
  stats:
    enabled: true
  metrics:
    enabled: true
  publishService:
    enabled: true
