rbac:
  create: true
controller:
  service:
    annotations:
      # Enable PROXY protocol
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      # Ensure the ELB idle timeout is less than nginx keep-alive timeout. By default,
      # NGINX keep-alive is set to 75s. If using WebSockets, the value will need to be
      # increased to '3600' to avoid any potential issues.
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  # configMapNamespace: "ingress-nginx"
  config:
    use-proxy-protocol: "true"
  # stats:
  #   enabled: true
  # metrics:
  #   enabled: true
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  publishService:
    enabled: true
defaultBackend:
  enabled: false
