"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "argocd"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "argocd"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "argo-cd"
    "helm":
      "parameters":
      - "name": "server.rbacConfig.policy\\.csv"
        "value": |
          g, administrators, role:admin
      - "name": "server.ingress.tls[0].hosts[0]"
        "value": "argocd.swiss-army-kube.swiss.sak.ninja"
      - "name": "server.ingress.hosts[0]"
        "value": "argocd.swiss-army-kube.swiss.sak.ninja"
      - "name": "server.ingress.tls[0].secretName"
        "value": "argocd-swiss-army-kube.swiss.sak.ninja-tls"
      - "name": "server.ingress.annotations.kubernetes\\.io/ingress\\.class"
        "value": "nginx"
      - "name": "server.ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/ssl-redirect"
        "value": "false"
      - "name": "configs.secret.argocdServerAdminPassword"
        "value": "$2a$10$RvXuduIMW5ZibjAXCFn6fO/Mv4ycFSOD3Ls9ow0zMD8yyr/98352a"
      - "name": "configs.secret.bitbucketServerSecret"
        "value": ""
      - "name": "configs.secret.bitbucketUUID"
        "value": ""
      - "name": "configs.secret.createSecret"
        "value": "true"
      - "name": "configs.secret.githubSecret"
        "value": ""
      - "name": "configs.secret.gitlabSecret"
        "value": ""
      - "name": "configs.secret.gogsSecret"
        "value": ""
      - "name": "dex.enabled"
        "value": "false"
      - "name": "global.securityContext.fsGroup"
        "value": "999"
      - "name": "installCRDs"
        "value": "false"
      - "name": "kubeVersionOverride"
        "value": "1.18"
      - "name": "repoServer.env[0].name"
        "value": "AWS_DEFAULT_REGION"
      - "name": "repoServer.env[0].value"
        "value": "eu-central-1"
      - "name": "repoServer.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::641456973426:role/swiss-army-kube_argocd"
      - "name": "repoServer.serviceAccount.create"
        "value": "true"
      - "name": "repoServer.volumeMounts[0].mountPath"
        "value": "/opt/decryptor/bin"
      - "name": "repoServer.volumeMounts[0].name"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.items[0].key"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.items[0].path"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.name"
        "value": "argocd-decryptor"
      - "name": "repoServer.volumes[0].name"
        "value": "decryptor"
      - "name": "server.config.configManagementPlugins"
        "value": |
          - "generate":
              "args":
              - "/opt/decryptor/bin/decryptor"
              "command":
              - "/usr/bin/python3"
            "init":
              "args":
              - "install"
              - "boto3"
              "command":
              - "/usr/bin/pip3"
            "name": "decryptor"
      - "name": "server.config.repositories"
        "value": |+
          - url: https://github.com/provectus/swiss-army-kube
            usernameSecret:
              name: argocd-repo-credentials-secret
              key: username
            passwordSecret:
              name: argocd-repo-credentials-secret
              key: password

      - "name": "server.extraArgs[0]"
        "value": "--insecure"
      - "name": "server.ingress.enabled"
        "value": "true"
      - "name": "server.ingress.paths[0]"
        "value": "/"
      - "name": "server.rbacConfig.policy\\.default"
        "value": "role:readonly"
      - "name": "server.service.type"
        "value": "ClusterIP"
    "repoURL": "https://argoproj.github.io/argo-helm"
    "targetRevision": "3.6.6"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
