"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "argocd"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "argocd"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "argo-cd"
    "helm":
      "parameters":
      - "name": "server.rbacConfig.policy\\.csv"
        "value": |
          g, administrators, role:admin
      - "name": "server.ingress.tls[0].hosts[0]"
        "value": "argocd.swiss-army-kube-sub2zero.swiss.sak.ninja"
      - "name": "server.ingress.hosts[0]"
        "value": "argocd.swiss-army-kube-sub2zero.swiss.sak.ninja"
      - "name": "server.ingress.tls[0].secretName"
        "value": "argocd-swiss-army-kube-sub2zero.swiss.sak.ninja-tls"
      - "name": "server.ingress.annotations.kubernetes\\.io/ingress\\.class"
        "value": "nginx"
      - "name": "server.ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/ssl-redirect"
        "value": "false"
      - "name": "configs.knownHosts.data.ssh_known_hosts"
        "value": ""
      - "name": "configs.secret.bitbucketServerSecret"
        "value": ""
      - "name": "configs.secret.bitbucketUUID"
        "value": ""
      - "name": "configs.secret.createSecret"
        "value": "true"
      - "name": "configs.secret.githubSecret"
        "value": ""
      - "name": "configs.secret.gitlabSecret"
        "value": ""
      - "name": "configs.secret.gogsSecret"
        "value": ""
      - "name": "dex.enabled"
        "value": "false"
      - "name": "global.securityContext.fsGroup"
        "value": "999"
      - "name": "installCRDs"
        "value": "false"
      - "name": "kubeVersionOverride"
        "value": "1.18"
      - "name": "repoServer.env[0].name"
        "value": "AWS_DEFAULT_REGION"
      - "name": "repoServer.env[0].value"
        "value": "eu-north-1"
      - "name": "repoServer.initContainers[0].args[0]"
        "value": "wget -O kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
          && chmod +x kustomize && mv kustomize /custom-binaries"
      - "name": "repoServer.initContainers[0].command[0]"
        "value": "sh"
      - "name": "repoServer.initContainers[0].command[1]"
        "value": "-c"
      - "name": "repoServer.initContainers[0].image"
        "value": "alpine:3.15"
      - "name": "repoServer.initContainers[0].name"
        "value": "download-kustomize"
      - "name": "repoServer.initContainers[0].volumeMounts[0].mountPath"
        "value": "/custom-binaries"
      - "name": "repoServer.initContainers[0].volumeMounts[0].name"
        "value": "custom-binaries"
      - "name": "repoServer.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::245582572290:role/swiss-army-kube-sub2zero_argocd"
      - "name": "repoServer.serviceAccount.create"
        "value": "true"
      - "name": "repoServer.serviceAccount.name"
        "value": "argocd-repo-server"
      - "name": "repoServer.volumeMounts[0].mountPath"
        "value": "/opt/decryptor/bin"
      - "name": "repoServer.volumeMounts[0].name"
        "value": "decryptor"
      - "name": "repoServer.volumeMounts[1].mountPath"
        "value": "/custom-binaries"
      - "name": "repoServer.volumeMounts[1].name"
        "value": "custom-binaries"
      - "name": "repoServer.volumeMounts[1].subPath"
        "value": "kustomize"
      - "name": "repoServer.volumes[0].configMap.items[0].key"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.items[0].path"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.name"
        "value": "argocd-decryptor"
      - "name": "repoServer.volumes[0].name"
        "value": "decryptor"
      - "name": "repoServer.volumes[1].name"
        "value": "custom-binaries"
      - "name": "server.config.configManagementPlugins"
        "value": |
          - "generate":
              "args":
              - "/opt/decryptor/bin/decryptor"
              "command":
              - "/usr/bin/python3"
            "init":
              "args":
              - "install"
              - "boto3"
              "command":
              - "/usr/bin/pip3"
            "name": "decryptor"
      - "name": "server.config.kustomize\\.path\\.v3\\.2\\.0"
        "value": "/custom-binaries"
      - "name": "server.config.repositories"
        "value": |+
          - url: https://github.com/sub2zero/swiss-army-kube
            usernameSecret:
              name: argocd-repo-credentials-secret
              key: username
            passwordSecret:
              name: argocd-repo-credentials-secret
              key: password

      - "name": "server.extraArgs[0]"
        "value": "--insecure"
      - "name": "server.ingress.enabled"
        "value": "true"
      - "name": "server.ingress.paths[0]"
        "value": "/"
      - "name": "server.rbacConfig.policy\\.default"
        "value": "role:readonly"
      - "name": "server.service.type"
        "value": "ClusterIP"
      "values": |
        "configs":
          "secret":
            "argocdServerAdminPassword": "$2a$10$DgujvSyIqaBBRWleHCkY0eQvvktLJkPN8ykFYkAVaDS5DtnvMo6zG"
    "repoURL": "https://argoproj.github.io/argo-helm"
    "targetRevision": "3.33.5"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
