apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.9
    chart: external-secrets

    helm:


      values: |
        securityContext:
          runAsNonRoot: true
          fsGroup: 1000
        
        env:
          AWS_REGION: eu-north-1
          AWS_DEFAULT_REGION: eu-north-1
          POLLER_INTERVAL_MILLISECONDS: 30000
        
        serviceAccount:
          annotations: 
            eks.amazonaws.com/role-arn: arn:aws:iam::245582572290:role/swiss-army-kube-sub2zero_external-secrets
          
        fullnameOverride: external-secrets
        


  project: default
  syncPolicy:
    automated: {}
