apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 6.0.0
    chart: kubernetes-external-secrets
    helm:
      parameters:
        - name: 'env.POLLER_INTERVAL_MILLISECONDS'
          value: '50000'
          forceString: true
      values: |
        securityContext:
          runAsNonRoot: true
          fsGroup: 1000
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          POLLER_INTERVAL_MILLISECONDS: 30000
        serviceAccount:
          annotations: 
            eks.amazonaws.com/role-arn: arn:aws:iam::SOME_ACCOUNT_NUMBER:role/external-secrets-your-cluster
  project: default
  syncPolicy:
    automated: {}
