apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: argo
images:
- name: argoproj/argoui
  newName: argoproj/argoui
  newTag: v2.3.0
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: v2.3.0
configMapGenerator:
- name: workflow-controller-parameters
  envs:
    - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
- name: clusterDomain
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterDomain
