apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fsx-csi-external-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fsx-csi-external-provisioner-role
subjects:
- kind: ServiceAccount
  name: fsx-csi-controller-sa
  namespace: kube-system
