apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: pipelines-ui
  app.kubernetes.io/instance: pipelines-ui-0.2.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: pipelines-ui
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.2.0
configurations:
- overlays/istio/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/istio/virtual-service.yaml
- overlays/application/application.yaml
