name: "Set Labels"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  SetLabel:
    runs-on: ubuntu-latest
    name: Set Labels
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: > 
            [
            {"keywords": ["bug", "error"], "labels": ["BUG"], "assignees": [""]},
            {"keywords": ["help", "guidance"], "labels": ["help-wanted"], "assignees": [""]},
            {"keywords": ["feature", "enhancement", "feat"], "labels": ["enhancement"], "assignees": [""]},
            {"keywords": ["docs", "Docs"], "labels": ["docs"], "assignees": [""]},
            {"keywords": ["chore", "skip"], "labels": ["skip-changelog"], "assignees": [""]},
            {"keywords": ["argocd", "argo-cd"], "labels": ["sak-argocd"], "assignees": [""]},
            {"keywords": ["albcontroller", "alb-controller"], "labels": ["sak-alb"], "assignees": [""]},
            {"keywords": ["cognito", "Cognito"], "labels": ["sak-cognito"], "assignees": [""]},
            {"keywords": ["certificate", "letsencrypt"], "labels": ["sak-cert-manager"], "assignees": [""]},
            {"keywords": ["efk", "kibana", "elastic"], "labels": ["sak-efk"], "assignees": [""]},
            {"keywords": ["external-dns", "externaldns"], "labels": ["sak-external-dns"], "assignees": [""]},
            {"keywords": ["kubeflow"], "labels": ["sak-kubeflow"], "assignees": [""]},
            {"keywords": ["eks", "kubernetes"], "labels": ["sak-kubernetes"], "assignees": [""]},
            {"keywords": ["nginx", "ingress"], "labels": ["sak-nginx"], "assignees": [""]},
            {"keywords": ["monitoring", "prometheus"], "labels": ["sak-prometheus"], "assignees": [""]},
            {"keywords": ["asg", "scaling"], "labels": ["sak-scaling"], "assignees": [""]},
            {"keywords": ["oauth"], "labels": ["sak-oauth"], "assignees": [""]},
            {"keywords": ["vpc"], "labels": ["sak-vpc"], "assignees": [""]}
            ]
          github-token: "${{ secrets.GITHUB_TOKEN }}"

#{"keywords": ["help", "guidance"], "labels": ["help-wanted"], "assignees": ["username"]}